# KERAS FUNDAMENTALS
https://keras.io/getting-started/sequential-model-guide/

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation

Create Sequential model. Add layers. Compile with optimizer, loss, metrics etc

## Binary Classification

Single layer Perceptron  

In [ ]:
# For a single-input model with 2 classes (binary classification):

model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

For binary classification inputs are 1D arrays (consider them as 1D images) that need to fall into two buckets.  
Hence input data are rows of 1D Images.  
Label data are rows of 0 or 1.

In [ ]:
# Generate dummy data
import numpy as np
data = np.random.random((500, 100))
print(data.shape)
labels = np.random.randint(2, size=(500, 1)) # 0-1
print(labels.shape)
# print(labels)

In [ ]:
# Train the model, iterating on the data in batches of 32 samples
model.fit(data, labels, epochs=10, batch_size=32)

## Multilayer Perceptron (MLP) for multi-class softmax classification:
https://keras.io/getting-started/sequential-model-guide/

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

# Generate dummy data
import numpy as np
x_train = np.random.random((1000, 20))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
x_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)

model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

model.fit(x_train, y_train,
          epochs=20,
          batch_size=128)
score = model.evaluate(x_test, y_test, batch_size=128)
print(score)

## VGG-like convnet 
### Inputs are rows of 100x100x3 images
>* 100x100 images with 3 channels -> (100, 100, 3) tensors.
>* Ouputs are i.e.

### Outputs are rows of 1 hot encoded arrays of size num_classes
>* Output is in y_train

```
y_train = keras.utils.to_categorical(np.random.randint(10, size=(3, 1)), num_classes=10)
print(y_train)

1 hot encoded Output:
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
```

In [ ]:
x_train = np.random.random((1, 10, 10, 3))
#print(x_train)
classes = np.random.randint(10, size=(3, 1))
print(classes)
y_train = keras.utils.to_categorical(np.random.randint(10, size=(3, 1)), num_classes=10)
print(y_train)

In [7]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.optimizers import SGD
from keras.utils import to_categorical, plot_model

# Generate dummy data
x_train = np.random.random((100, 100, 100, 3))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)
x_test = np.random.random((20, 100, 100, 3))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(20, 1)), num_classes=10)

model = Sequential()
# input: 100x100 images with 3 channels -> (100, 100, 3) tensors.
# this applies 32 convolution filters of size 3x3 each.
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(100, 100, 3)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

model.summary()
plot_model(model, to_file='mlp-mnist.png', show_shapes=True)

model.compile(loss='categorical_crossentropy', optimizer=sgd)

#model.fit(x_train, y_train, batch_size=32, epochs=10)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_24 (Conv2D)           (None, 98, 98, 32)        896       
_________________________________________________________________
conv2d_25 (Conv2D)           (None, 96, 96, 32)        9248      
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 48, 48, 32)        0         
_________________________________________________________________
dropout_19 (Dropout)         (None, 48, 48, 32)        0         
_________________________________________________________________
conv2d_26 (Conv2D)           (None, 46, 46, 64)        18496     
_________________________________________________________________
conv2d_27 (Conv2D)           (None, 44, 44, 64)        36928     
_________________________________________________________________
max_pooling2d_14 (MaxPooling (None, 22, 22, 64)        0         
__________