In [1]:
import numpy as np

## NumPy User Guide

Tip: Step through each and every cell for memorization.    
Good single page complete reference.

https://docs.scipy.org/doc/numpy/user/index.html

In [2]:
a = np.arange(15).reshape(3, 5)
print(a)
# Shape
print(a.shape)
# Num dimensions
print(a.ndim)
# Data type name
print(a.dtype.name)
# Item size
print(a.itemsize)
# Total size
print(a.size)

print(type(a))

b = np.array([6, 7, 8])
print(b)

print(type(b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
4
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>


In [ ]:
# Array Creation
a = np.array([2,3,4])
print(a)

print(a.dtype)

b = np.array([1.2, 3.5, 5.1])
print(b.dtype)

### Array Creation
a = np.array(1,2,3,4)    # WRONG  
a = np.array([1,2,3,4])  # RIGHT

The type of the array can also be explicitly specified at creation time:

In [ ]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)
c = np.array( [ [1,2], [3,4] ], dtype=np.int16 )
print(c)
c = np.array( [ [1,2], [3,4] ], dtype=np.complex128)
print(c)

### Datatypes
Full book (classic good ref):  https://jakevdp.github.io/PythonDataScienceHandbook/  
https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html  

<u>Data type	Description</u>  
bool_	Boolean (True or False) stored as a byte  
int_	Default integer type (same as C long; normally either int64 or int32)  
intc	Identical to C int (normally int32 or int64)  
intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)  
int8	Byte (-128 to 127)  
int16	Integer (-32768 to 32767)  
int32	Integer (-2147483648 to 2147483647)  
int64	Integer (-9223372036854775808 to 9223372036854775807)  
uint8	Unsigned integer (0 to 255)  
uint16	Unsigned integer (0 to 65535)  
uint32	Unsigned integer (0 to 4294967295)  
uint64	Unsigned integer (0 to 18446744073709551615)  
float_	Shorthand for float64.  
float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa  
float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa  
float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa  
complex_	Shorthand for complex128.  
complex64	Complex number, represented by two 32-bit floats  
complex128	Complex number, represented by two 64-bit floats  

In [ ]:
# Quick Arrays with Initial PLaceholder content

np.zeros( (3,4) )

np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

np.empty( (2,3) )                                 # uninitialized, output may vary

In [ ]:
# np.arange (start, end , step)
np.arange( 10, 30, 5 )

np.arange( 0, 2, 0.3 )                 # it accepts float arguments

np.arange(0, 15, 0.4)

In [ ]:
# np.linspace(start, end, number_of_elements)

from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

x = np.linspace( 0, 2*pi, 50 )        # useful to evaluate function at lots of points
f = np.sin(x) # Use of function on entire array
print(f)

## Basic Operations

In [ ]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(b)

c = a-b
print(c)

print(b**2)

print(10*np.sin(a))

print(a<35)

In [ ]:
# Matrix operations
A = np.array( [[1,1],
            [0,1]] )
B = np.array( [[2,0],
            [3,4]] )
A * B                       # elementwise product (Note this is not dot prod)


A @ B                       # matrix product


A.dot(B)                    # another matrix product

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [ ]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

b += a
b

#a += b  # error: b is not automatically converted to integer type

In [ ]:
# Sum, min, max

a = np.random.random((2,3))
a

a.sum()

a.min()

a.max()

# With axis

b = np.arange(12).reshape(3,4)
b

b.sum(axis=0)                            # sum of each column


b.min(axis=1)                            # min of each row


b.cumsum(axis=1)                         # cumulative sum along each row

In [3]:
# Universal functions
B = np.arange(3)
B

np.exp(B)

np.sqrt(B)

C = np.array([2., -1., 4.])
np.add(B, C)


array([2., 0., 6.])

See also:  
all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

## Indexing, slicing, iterating

Slicing an array returns a view of it

In [7]:
a = np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [8]:
a[2]

8

In [9]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [14]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
print(a)

a = a[ : :-1]                                 # reversed a
print(a)
for i in a:
    print(i**2)

[-1000   512 -1000   216 -1000 -1000    27 -1000     1 -1000]
[-1000     1 -1000    27 -1000 -1000   216 -1000   512 -1000]
1000000
1
1000000
729
1000000
1000000
46656
1000000
262144
1000000


## np.fromFunction Usage

In [15]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

<b>Multidimensional</b> arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [16]:
# Indexing and slicing multidimentional arrays

b[2,3]

b[0:5, 1]                       # each row in the second column of b

b[ : ,1]                        # equivalent to the previous example

b[1:3, : ]                      # each column in the second and third row of b


array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [18]:
q = np.arange(0,100).reshape(5,5,4)
q

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [27]:
# Slicing multidim arrays
q[1:3,:,2]
q[1:3,:,::2]

array([[[20, 22],
        [24, 26],
        [28, 30],
        [32, 34],
        [36, 38]],

       [[40, 42],
        [44, 46],
        [48, 50],
        [52, 54],
        [56, 58]]])

## Stacking together different arrays
Several arrays can be stacked together along different axes:

In [28]:
a = np.floor(10*np.random.random((2,2)))
a


b = np.floor(10*np.random.random((2,2)))
b

np.vstack((a,b))

np.hstack((a,b))

array([[5., 0., 9., 3.],
       [3., 6., 0., 3.]])

In [29]:
## Copies and Views

In [31]:
# Note: no copy during direct assignment

a = np.arange(12)
b = a            # no new object is created
print(b is a)           # a and b are two names for the same ndarray object

b.shape = 3,4    # changes the shape of a
a.shape

True


(3, 4)

In [32]:
# View or Shallow Copy

c = a.view()
c is a

c.base is a                        # c is a view of the data owned by a

c.flags.owndata


c.shape = 2,6                      # a's shape doesn't change
a.shape

c[0,4] = 1234                      # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Slicing an array returns a view of it

### Deep Copy¶

In [ ]:
d = a.copy()                          # a new array object with new data is created
d is a

d.base is a                           # d doesn't share anything with a

d[0,0] = 9999
a

## Functions and Methods Overview  
Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines for the full list.  

### Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like
### Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
### Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
### Questions
all, any, nonzero, where
### Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort
### Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
### Basic Statistics
cov, mean, std, var
### Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot

## Random

Main: https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html

rand(d0, d1, …, dn)	Random values in a given shape.  
randn(d0, d1, …, dn)	Return a sample (or samples) from the “standard normal” distribution.  
randint(low[, high, size, dtype])	Return random integers from low (inclusive) to high (exclusive).  
random_integers(low[, high, size])	Random integers of type np.int between low and high, inclusive.  
random_sample([size])	Return random floats in the half-open interval [0.0, 1.0).  
random([size])	Return random floats in the half-open interval [0.0, 1.0).  
ranf([size])	Return random floats in the half-open interval [0.0, 1.0).  
sample([size])	Return random floats in the half-open interval [0.0, 1.0).  
choice(a[, size, replace, p])	Generates a random sample from a given 1-D array  
bytes(length)	Return random bytes.  

In [37]:
d = np.random.random((10)).reshape(2,5) # or np.random.random((2,5))
print(d)

[[0.93566626 0.57968101 0.94233246 0.14273154 0.15864411]
 [0.87573354 0.37852983 0.35122704 0.54296751 0.65726031]]


In [39]:
d = np.random.randint(10)
print(d)

np.random.randint(2, size=10)

np.random.randint(1, size=10)

np.random.randint(5, size=(2, 4))

4
